name: Cypress Tests

on: push
    #repository_dispatch:
    #schedule:
        #- cron: "0 17 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.2

      - name: Cypress run
        uses: cypress-io/github-action@v6 # use the explicit version number
        with:
            config-file: cypress.config.ts
            browser: chrome
            headed: false
            record: true

      - name: Store screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: Cypress-screenshots
            path: cypress/reports/screenshots
        
      - name: store reports directory
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: reports-directory-othertests
            path: cypress/reports

        