name: Cypress Tests

on: push

jobs:
  cypress-othertests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: npm ci
        run: |
          echo "Node version"
          node -v
          echo "NPM version"
          npm -v
          npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6 # use the explicit version number
        with:
            browser: chrome
            record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}